apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  labels:
    nims/workflowName: test-workflow
  name: docker-hackathon-rose-5
  namespace: dafni-nims-workflow-staging
spec:
  entrypoint: dag
  serviceAccountName: nims-workflow-staging
  templates:
  - container:
      args:
      - '{{inputs.parameters.dataset-version-uid}}'
      - '{{inputs.parameters.volume-path}}'
      command:
      - python
      - dataretrieval.py
      env:
      - name: NID_URL
        value: https://dafni-nid-api.staging.dafni.rl.ac.uk/nid
      - name: VOLUME_MOUNT_PATH
        value: /data/
      - name: USER_TOKEN
        value: 4de68c3b-4db0-450e-8e11-85a627ce1a7f
      - name: KEYCLOAK_ENDPOINT
        value: https://keycloak.staging.dafni.rl.ac.uk/auth/
      - name: KEYCLOAK_REALM
        value: Staging
      - name: KEYCLOAK_CLIENT
        value: dafni-main
      - name: KEYCLOAK_CLIENT_SECRET
        value: '"55f54120-ed4f-46e9-9c1c-db4cc719f937"'
      - name: KEYCLOAK_USERNAME
        value: dafni-service-account
      - name: KEYCLOAK_PASSWORD
        value: .dqiDbnu9Kpvw7cYZAQRC8cFEae6pJ
      image: reg.dafni.rl.ac.uk/dafni/nims/management-container/staging
      resources:
        limits:
          cpu: '16'
          ephemeral-storage: 50Gi
          memory: 128Gi
        requests:
          cpu: 200m
          ephemeral-storage: 10Gi
          memory: 128Mi
      volumeMounts:
      - mountPath: /data/
        name: shared-workflow-volume
    daemon: false
    inputs:
      parameters:
      - name: dataset-version-uid
      - name: volume-path
    metadata:
      labels:
        nims/stepId: data-retrieval-step
        nims/userId: 1d26cdb8-cb61-4ae6-b819-892a969bdb96
        nims/workflowId: 231f6527-c802-4027-be0b-33497334b08f
    name: data-retrieval-step
  - container:
      image: quay.io/ukhomeofficedigital/vault-sidekick
      args:
        - -logtostderr
        - -ca-cert=/data/vault-ca.crt
        - -cn=secret:secret/data/harbor/modelbuild-hack:file=/kaniko/config,fmt=json
      env:
      - name: VAULT_ADDR
        value: https://vault.vault.svc.cluster.local:8200
      - name: VAULT_OUTPUT
        value: /secrets
      - name: VAULT_SIDEKICK_ROLE
        value: modelbuild
      - name: VAULT_AUTH_METHOD
        value: kubernetes
      volumeMounts:
      - name: kaniko-secret
        mountPath: /kaniko
      - mountPath: /data/
        name: shared-workflow-volume
    name: vault-sidekick
  - container:
      image: gcr.io/kaniko-project/executor:latest
      imagePullPolicy: IfNotPresent
      args: 
        - --dockerfile=/workspace/Dockerfile
        - --context=dir://workspace
        - --destination=docker-hackathon-docker-image-builder/rose
      resources:
        limits:
          cpu: '16'
          ephemeral-storage: 50Gi
          memory: 128Gi
        requests:
          cpu: '2'
          ephemeral-storage: 10Gi
          memory: 32Gi
      volumeMounts:
      - mountPath: /data/
        name: shared-workflow-volume
      - name: kaniko-secret
        mountPath: /kaniko/.docker
    name: dockerbuild
  - container:
      image: registry.k8s.io/git-sync/git-sync:v3.6.4
      imagePullPolicy: IfNotPresent
      args: 
        - --one-time=true
        - --repo=https://github.com/dafnifacility/dafni-example-models.git
        - --dest=/data
      resources:
        limits:
          cpu: '16'
          ephemeral-storage: 50Gi
          memory: 128Gi
        requests:
          cpu: '2'
          ephemeral-storage: 10Gi
          memory: 32Gi
      volumeMounts:
      - mountPath: /data/
        name: shared-workflow-volume
    name: gitsync
  - dag:
      tasks:
      - arguments:
          parameters:
          - name: dataset-version-uid
            value: e7da63b9-4737-4528-a19b-958d65b7562b
          - name: volume-path
            value: '["/data"]'
        dependencies: []
        name: dataretrieval
        template: data-retrieval-step
      - dependencies: [dataretrieval]
        name: vault
        template: vault-sidekick
      - dependencies: [vault]
        name: gitsync
        template: gitsync
      - dependencies: [gitsync]
        name: dockerbuild
        template: dockerbuild
    name: dag
  volumeClaimTemplates:
  - metadata:
      name: shared-workflow-volume
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 128Gi
      storageClassName: nfs-client
  - metadata:
      name: kaniko-secret
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 10Gi
      storageClassName: nfs-client
